-- =====================================================================
-- 03_governance.sql  |  Amar Bank Workshop  |  Session 3 (Data Governance)
-- Tags, Dynamic Data Masking, Row Access Policy, Projection Policy,
-- Data Metric Functions (DMF), and RBAC. Applied to Session 1 tables.
-- Run as ACCOUNTADMIN (or a role with the right grants).
-- =====================================================================
USE DATABASE AMAR_WORKSHOP;
USE SCHEMA GOVERNANCE;
USE WAREHOUSE AMAR_WORKSHOP_WH;

-- ---- 1) RBAC roles ---------------------------------------------------
CREATE ROLE IF NOT EXISTS AMAR_DATA_ENGINEER;
CREATE ROLE IF NOT EXISTS AMAR_ANALYST;
CREATE ROLE IF NOT EXISTS AMAR_AUDITOR;

GRANT USAGE ON DATABASE AMAR_WORKSHOP TO ROLE AMAR_DATA_ENGINEER;
GRANT USAGE ON DATABASE AMAR_WORKSHOP TO ROLE AMAR_ANALYST;
GRANT USAGE ON DATABASE AMAR_WORKSHOP TO ROLE AMAR_AUDITOR;
GRANT USAGE ON ALL SCHEMAS IN DATABASE AMAR_WORKSHOP TO ROLE AMAR_DATA_ENGINEER;
GRANT USAGE ON ALL SCHEMAS IN DATABASE AMAR_WORKSHOP TO ROLE AMAR_ANALYST;
GRANT USAGE ON ALL SCHEMAS IN DATABASE AMAR_WORKSHOP TO ROLE AMAR_AUDITOR;
GRANT SELECT ON ALL TABLES IN SCHEMA GOLD TO ROLE AMAR_ANALYST;
GRANT SELECT ON ALL TABLES IN SCHEMA SILVER TO ROLE AMAR_DATA_ENGINEER;
GRANT SELECT ON ALL TABLES IN SCHEMA BRONZE TO ROLE AMAR_DATA_ENGINEER;
-- hierarchy: ANALYST -> DE -> AUDITOR -> SYSADMIN
GRANT ROLE AMAR_ANALYST TO ROLE AMAR_DATA_ENGINEER;
GRANT ROLE AMAR_DATA_ENGINEER TO ROLE AMAR_AUDITOR;
GRANT ROLE AMAR_AUDITOR TO ROLE SYSADMIN;

-- ---- 2) Tags ---------------------------------------------------------
CREATE TAG IF NOT EXISTS GOVERNANCE.PII_TYPE
    ALLOWED_VALUES 'NIK','NPWP','NAME','PHONE','EMAIL','INCOME','NONE';
CREATE TAG IF NOT EXISTS GOVERNANCE.DATA_CLASSIFICATION
    ALLOWED_VALUES 'PUBLIC','INTERNAL','CONFIDENTIAL','RESTRICTED';

ALTER TABLE SILVER.STG_CUSTOMERS MODIFY COLUMN nik    SET TAG GOVERNANCE.PII_TYPE = 'NIK';
ALTER TABLE SILVER.STG_CUSTOMERS MODIFY COLUMN npwp   SET TAG GOVERNANCE.PII_TYPE = 'NPWP';
ALTER TABLE SILVER.STG_CUSTOMERS MODIFY COLUMN phone  SET TAG GOVERNANCE.PII_TYPE = 'PHONE';
ALTER TABLE SILVER.STG_CUSTOMERS MODIFY COLUMN email  SET TAG GOVERNANCE.PII_TYPE = 'EMAIL';
ALTER TABLE SILVER.STG_CUSTOMERS SET TAG GOVERNANCE.DATA_CLASSIFICATION = 'CONFIDENTIAL';

-- ---- 3) Dynamic Data Masking ----------------------------------------
CREATE OR REPLACE MASKING POLICY GOVERNANCE.MASK_NIK AS (val STRING) RETURNS STRING ->
    CASE WHEN CURRENT_ROLE() IN ('ACCOUNTADMIN','AMAR_AUDITOR') THEN val
         WHEN CURRENT_ROLE() = 'AMAR_DATA_ENGINEER' THEN CONCAT(REPEAT('X', LENGTH(val) - 4), RIGHT(val, 4))
         ELSE 'XXXXXXXXXXXXXXXX' END;

CREATE OR REPLACE MASKING POLICY GOVERNANCE.MASK_EMAIL AS (val STRING) RETURNS STRING ->
    CASE WHEN CURRENT_ROLE() IN ('ACCOUNTADMIN','AMAR_AUDITOR') THEN val
         ELSE REGEXP_REPLACE(val, '^[^@]+', '****') END;

CREATE OR REPLACE MASKING POLICY GOVERNANCE.MASK_PHONE AS (val STRING) RETURNS STRING ->
    CASE WHEN CURRENT_ROLE() IN ('ACCOUNTADMIN','AMAR_AUDITOR') THEN val
         ELSE CONCAT(LEFT(val,4),'XXXXXX') END;

CREATE OR REPLACE MASKING POLICY GOVERNANCE.MASK_INCOME AS (val NUMBER) RETURNS NUMBER ->
    CASE WHEN CURRENT_ROLE() IN ('ACCOUNTADMIN','AMAR_AUDITOR','AMAR_DATA_ENGINEER') THEN val ELSE NULL END;

ALTER TABLE SILVER.STG_CUSTOMERS MODIFY COLUMN nik   SET MASKING POLICY GOVERNANCE.MASK_NIK;
ALTER TABLE SILVER.STG_CUSTOMERS MODIFY COLUMN email SET MASKING POLICY GOVERNANCE.MASK_EMAIL;
ALTER TABLE SILVER.STG_CUSTOMERS MODIFY COLUMN phone SET MASKING POLICY GOVERNANCE.MASK_PHONE;
ALTER TABLE SILVER.STG_CUSTOMERS MODIFY COLUMN monthly_income SET MASKING POLICY GOVERNANCE.MASK_INCOME;

-- ---- 4) Row Access Policy (province-based) --------------------------
CREATE OR REPLACE ROW ACCESS POLICY GOVERNANCE.RAP_PROVINCE AS (province STRING) RETURNS BOOLEAN ->
    CURRENT_ROLE() IN ('ACCOUNTADMIN','AMAR_AUDITOR','AMAR_DATA_ENGINEER')
    OR province = 'DKI Jakarta';   -- ANALYST sees only Jakarta (demo)
ALTER TABLE SILVER.STG_CUSTOMERS ADD ROW ACCESS POLICY GOVERNANCE.RAP_PROVINCE ON (province);

-- ---- 5) Projection Policy (block projecting NIK for ANALYST) ---------
CREATE OR REPLACE PROJECTION POLICY GOVERNANCE.PROJ_NIK AS () RETURNS PROJECTION_CONSTRAINT ->
    CASE WHEN CURRENT_ROLE() IN ('AMAR_ANALYST') THEN PROJECTION_CONSTRAINT(ALLOW => FALSE)
         ELSE PROJECTION_CONSTRAINT(ALLOW => TRUE) END;
ALTER TABLE SILVER.STG_CUSTOMERS MODIFY COLUMN nik SET PROJECTION POLICY GOVERNANCE.PROJ_NIK;

-- ---- 6) Data Metric Functions (DMF) ---------------------------------
-- custom: count out-of-range credit scores
CREATE OR REPLACE DATA METRIC FUNCTION GOVERNANCE.DMF_CREDIT_SCORE_RANGE(arg TABLE(score NUMBER))
RETURNS NUMBER AS $$ SELECT COUNT(*) FROM arg WHERE score < 300 OR score > 850 $$;

-- set a measurement schedule + attach system + custom DMFs
ALTER TABLE SILVER.STG_CUSTOMERS SET DATA_METRIC_SCHEDULE = 'TRIGGER_ON_CHANGES';
-- ALTER TABLE SILVER.STG_CUSTOMERS SET DATA_METRIC_SCHEDULE = '5 MINUTE';
ALTER TABLE SILVER.STG_CUSTOMERS ADD DATA METRIC FUNCTION SNOWFLAKE.CORE.NULL_COUNT ON (email);
ALTER TABLE SILVER.STG_CUSTOMERS ADD DATA METRIC FUNCTION SNOWFLAKE.CORE.DUPLICATE_COUNT ON (customer_id);
ALTER TABLE SILVER.STG_CUSTOMERS ADD DATA METRIC FUNCTION GOVERNANCE.DMF_CREDIT_SCORE_RANGE ON (credit_score);

-- review DMF results (after measurement runs):
-- SELECT * FROM TABLE(SNOWFLAKE.LOCAL.DATA_QUALITY_MONITORING_RESULTS(
--   REF_ENTITY_NAME => 'AMAR_WORKSHOP.SILVER.STG_CUSTOMERS', REF_ENTITY_DOMAIN => 'TABLE'))
--   ORDER BY measurement_time DESC;

-- ---- 7) Lineage / Horizon (run in Snowsight UI) ---------------------
-- Snowsight > Governance > Lineage on AMAR_WORKSHOP.GOLD.MART_CUSTOMER_360
-- shows: S3 -> BRONZE.RAW_* -> SILVER.STG_*/DIM_* -> GOLD.MART_*
